on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: start my test
        run: echo "#######################################################################################"
      - name: get url
        run: echo "https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"
      - name: create a file
        run: echo "i am a file" > myfile.txt
      - name: listing some dir
        run: |
          ls -l ${{ github.workspace }}
          ls -l /opt
          mkdir -p /opt/artifacts
      - name: listing opt dir
        run: ls -l /opt/
      - name: move file into artifact
        run: cp -f myfile.txt /opt/artifacts/
      - name: listing artifacts
        run: ls -l /opt/
